### ISSUE TITLE
Invalid maven url

### ISSUE THREAD

**Issue by rabacadabra** [reposilite-playground/javalin-openapi#21]
The dependencies cannot be resolved even after adding the following:

```
maven {
    url "https://repo.panda-lang.org/releases"
}
```

Also, https://repo.panda-lang.org/releases shows a 404

**Comment by dzikoysk** [comment]
Yeah, should be /releases, thanks!. The 404 is fine as it's Maven index, for UI use https://repo.panda-lang.org/#/releases

**Comment by dzikoysk** [comment]
Which dependencies?  Here's the working example:

https://github.com/dzikoysk/reposilite/blob/ec5254571b9e6c4f5365bb3dd8168e0ec1fb16de/reposilite-backend/build.gradle.kts#L78

**Comment by rabacadabra** [comment]
thanks!
