### ISSUE TITLE
Why i can not see the last version when using javalin bundle 4.4.0

### ISSUE THREAD

**Issue by oscarsan** [reposilite-playground/javalin-openapi#24]
QUESTION

Im trully missing the annotation OpenApiName but on my project which is using on pom bundle 4.4.0, and as i can see javalin-openapi 4.4.0 as described in maven central as last version is does not find this annotation.

**Comment by oscarsan** [comment]
Ok, thanks. Is there a reason why this has not been mergen on the oficcial javalin-openapi? I found funny there is no a simple way to document the object fields itself with descriptions.

**Comment by dzikoysk** [comment]
Take a look at:

* https://github.com/tipsy/javalin/issues/1296

OpenApi impl has a lot of related issues, this impl does not cover all of them (like e.g. integration with DSL)
